version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    networks:
      - network1
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - network1
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/

  account-svc:
    image: ${DOCKER_REGISTRY-}account-svc
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8009:8009
    networks:
      - network1

networks:
  network1: